apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: tinyproxy
  name: tinyproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tinyproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tinyproxy
    spec:
      containers:
      - image: dmilan/tinyproxy:latest
        name: tinyproxy
        command: ["/opt/docker-tinyproxy/run.sh","ANY"]
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: tinyproxy
  name: tinyproxy-svc
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8888
  selector:
    run: tinyproxy
  type: ClusterIP
